enableGlobalCache: true

enableImmutableInstalls: true

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 1w

npmScopes:
  proof.com:
    npmMinimalAgeGate: 0

yarnPath: .yarn/releases/yarn-4.17.0.cjs
